<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $jewel_default_price = $_product->getPrice();
    $default_number = $_product->getJewelDefaultNumber();

    $sceneTemplate = $this->getSceneTemplate();//http://s7d6.scene7.com/is/image/china/
    $sceneParams = $this->getSceneParams();//?qlt=100,1&hei=300&wei=300&op_sharpen=1
    $templateName = $this->getTemplateName();//test3
    $co = $this->getCoName();//get company name  china
    $param =$this->getScene7Param();//dim
?>

    <?php if (($jewels= $_product->getJewelNumber()) != ""):?>
    <label id="jewel_numer">Stones:</label>
    <select id="jewel_number" class="jewel_number" name="numberoption">
        <?php $jewel_number = explode(',',$jewels)?>
        <?php foreach ($jewel_number as $select_jewel_number):?>
        <option <?php if($select_jewel_number == $default_number)echo "selected=selected"?> value="<?php echo $select_jewel_number?>">
        <?php echo $select_jewel_number?>
        </option>
        <?php endforeach;?>
    </select>
    <?php endif;?>
    <?php
    //number of jewel and jewelgroup to display
    $group = $_product->getDefaultJewelgroup();
    $groupn = count($group);
    ?>
    <?php for($i=0;$i<$groupn;$i++):?>
        <div class="jewel_group<?php echo $group[$i]['position']?>" id="jewel_group<?php echo $group[$i]['position']?>">
            <label id="jewel<?php echo $group[$i]['position']?>" style="width:10px;display:block;"><?php echo $group[$i]['jewel_label']?></label>
            <select id="<?php echo $param.$group[$i]['position']?>" class="dim" name="sceneoption[<?php echo $group[$i]['jewel_label']?>]">
            <?php
            //get link between jewel and group
                $jewelLink = Mage::getModel('scenescene7/link')->getCollection()
                ->addFieldToFilter('group_id',$group[$i]['jewel_group'])->load();
                $jewelLink = $jewelLink->getData();
           // count the jewelNumber of group
                $number_jewel_link = count ($jewelLink);
            ?>
            <?php for($j=0;$j<$number_jewel_link;$j++):?>
            <?php 
                $jewelname = Mage::getModel('scenescene7/sceneitem')->load($jewelLink[$j]['sceneitem_id'])->getName();
                //get default jewel to judge the select
                $defaultjewel = Mage::getModel('scenescene7/sceneitem')->load($group[$i]['default_jewel'])->getName();
            ?>
                <option value="<?php echo $jewelLink[$j]['sceneitem_id']?>" <?php if ($jewelname == $defaultjewel) echo "selected=selected"?> >
                    <?php echo $jewelname;?>
            <?php endfor;?>
                </option>
            </select>
            <input type="hidden" value="<?php echo $group[$i]['angle'];?>"/>
         </div><br/>      
    <?php endfor;?>

<script type="text/javascript">
var maxNumber = <?php echo $groupn?>;
$j(document).ready(function(){
    updatePrice();
    updatePage($j('#jewel_number').val());
});
$j(document).ready(function(){
    $j('#jewel_number').change(function (){
        $j('div[id^="jewel_group"]').show();
        updatePage($j('#jewel_number').val());
        updateImage();
        updatePrice();
    });
});

function updatePage(number){
//according to selectNumber and group number to display the jewel group in the frontend 
var i,n,number = parseInt(number);

if (number < maxNumber){
   for ( i = number;i <= maxNumber; i++) {
       n = i+1;
        $j('.jewel_group'+n).hide();
}
}
}
var JewelArray = <?php echo $this->getJewelsJson();?>                  
$j(document).ready(function (){
    $j('select[class="dim"]').change(function (){
        updateImage();
        updatePrice();
    });
});

function updateImage(){
    var    variable = '';
    var    co ='<?php echo $co?>';
    //get select jewel number
    var    selecJewelnumber = $j('.jewel_number').val();
    //update the jewel number need some param
    var    urlparam = '<?php echo $sceneTemplate?>';
    var    param = '<?php echo $sceneParams?>';
    var    name = '<?php echo $templateName?>';
    var    sceneurl = urlparam+name+'-'+$j('.jewel_number').val()+ param;
    $j('select[class="dim"]').filter(':visible').each(function(){
        variable += '&$'+$j(this).attr('id')+'=is{'+co+'/'+JewelArray[$j(this).val()].code+'?rotate='+$j(this).parent().find('input').val()+'}';

        });
    $j('.scene7Image').attr('src',sceneurl+variable);
    $j('.srcoption').attr('value',$j('.scene7Image').attr('src'));
}

function updatePrice(){
    var baseprice = <?php echo $_product->getPrice();?>;
    var price = 0;
    $j('select[class="dim"]').filter(':visible').each(function(){
            price +=parseFloat(JewelArray[$j(this).val()].price);
     });
    var currency ='<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>';
        $j('.product-shop .price-box .price').text(currency+(price+baseprice).toString());
}
</script>