<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $baseurl = $this->getScene7Url();//http://s7ap1.scene7.com/is/image/china/test2-4?qlt=100,1&wid=360&hei=360&&op_sharpen=1
    $co = $this->getCoName();//get company name  china
    $param = $this->getScene7Param();//goods
?>
    <?php
    $group = $_product->getDefaultGoodsgroup();
    $groupn = count($group);
    ?>
    <?php for($i=0;$i<$groupn;$i++):?>
        <div class="goods_group<?php echo $group[$i]['position']?>" id="goods_group<?php echo $group[$i]['position']?>">
            <label id="goods<?php echo $group[$i]['position']?>" style="width:10px;display:block;"><?php echo $group[$i]['goods_label']?></label>
            <select id="<?php echo $param.$group[$i]['position']?>" class="goods" name="sceneoption[<?php echo $group[$i]['goods_label']?>]">
            <?php
            //get link between goods and group
                $goodsLink = Mage::getModel('scenescene7/link')->getCollection()
                ->addFieldToFilter('group_id',$group[$i]['goods_group'])->load();
                $goodsLink = $goodsLink->getData();
           // count the goodsNumber of group
                $number_goods_link = count ($goodsLink);
            ?>
            <?php for($j=0;$j<$number_goods_link;$j++):?>
            <?php 
                $goodsname = Mage::getModel('scenescene7/sceneitem')->load($goodsLink[$j]['sceneitem_id'])->getName();
                //get default goods to judge the select
                $defaultgoods = Mage::getModel('scenescene7/sceneitem')->load($group[$i]['default_goods'])->getName();
            ?>
                <option value="<?php echo $goodsLink[$j]['sceneitem_id']?>" <?php if ($goodsname == $defaultgoods) echo "selected=selected"?> >
                    <?php echo $goodsname;?>
            <?php endfor;?>
                </option>
            </select>
         </div><br/>      
    <?php endfor;?>
<script type="text/javascript">
$j(document).ready(function(){
    updatePrice();
});
var goodsArray = <?php echo $this->getGoodssJson();?>                  
$j(document).ready(function (){
    $j('select[class="goods"]').change(function (){
        updateImage();
        updatePrice();
    });
});

function updateImage(){
    var sceneurl = '<?php echo $baseurl?>';
    var variable ='';
    var co ='<?php echo $co?>';
    $j('select[class="goods"]').each(function(){
        variable += '&$'+$j(this).attr('id')+'=is{'+co+'/'+goodsArray[$j(this).val()].code+'}';

        });
    $j('.scene7Image').attr('src',sceneurl+variable);
    $j('.srcoption').attr('value',$j('.scene7Image').attr('src'));
}

function updatePrice(){
    var baseprice = <?php echo $_product->getPrice();?>;
    var price = 0;
    $j('select[class="goods"]').each(function(){
            price +=parseFloat(goodsArray[$j(this).val()].price);
     });
    var currency ='<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>';
    $j('.product-shop .price-box .price').text(currency+(price+baseprice).toString());
}
</script>