<?php
    /*
     *  http://s7ap1.scene7.com/is/image/china/test2?qlt=100,1&wid=360&hei=360&&op_sharpen=1
     *  &$dim4=is{china/green3?rotate=40}
     *  &$dim3=is{china/blue3?rotate=40}
     *  &$dim2=is{china/white3?rotate=40}
     *  &$dim1=is{china/pink3?rotate=30}
     * */ 
//$url = $this->getScene7Url();//base url
//$co = $this->getCoName();//get company name
$imgsrc = $this->getImg();//initial url
?>
<img src="<?php echo $imgsrc?>" alt="no image" class="scene7Image" />
<input type="hidden" name="srcoption" class="srcoption" value="<?php echo $imgsrc?>"/>
